package block

import (
	"github.com/df-mc/dragonfly/server/item"
	"github.com/df-mc/dragonfly/server/world"
)

//go:generate go run ../../cmd/blockhash -o hash.go .

// init registers all blocks implemented by Dragonfly.

func init() {
	world.DefaultBlockRegistry.RegisterBlock(Air{})
	world.DefaultBlockRegistry.RegisterBlock(Amethyst{})
	world.DefaultBlockRegistry.RegisterBlock(AncientDebris{})
	world.DefaultBlockRegistry.RegisterBlock(Andesite{Polished: true})
	world.DefaultBlockRegistry.RegisterBlock(Andesite{})
	world.DefaultBlockRegistry.RegisterBlock(Barrier{})
	world.DefaultBlockRegistry.RegisterBlock(Beacon{})
	world.DefaultBlockRegistry.RegisterBlock(Bedrock{InfiniteBurning: true})
	world.DefaultBlockRegistry.RegisterBlock(Bedrock{})
	world.DefaultBlockRegistry.RegisterBlock(BlueIce{})
	world.DefaultBlockRegistry.RegisterBlock(Bookshelf{})
	world.DefaultBlockRegistry.RegisterBlock(Bricks{})
	world.DefaultBlockRegistry.RegisterBlock(Calcite{})
	world.DefaultBlockRegistry.RegisterBlock(Clay{})
	world.DefaultBlockRegistry.RegisterBlock(Coal{})
	world.DefaultBlockRegistry.RegisterBlock(Cobblestone{Mossy: true})
	world.DefaultBlockRegistry.RegisterBlock(Cobblestone{})
	world.DefaultBlockRegistry.RegisterBlock(CraftingTable{})
	world.DefaultBlockRegistry.RegisterBlock(DeadBush{})
	world.DefaultBlockRegistry.RegisterBlock(DeepslateBricks{Cracked: true})
	world.DefaultBlockRegistry.RegisterBlock(DeepslateBricks{})
	world.DefaultBlockRegistry.RegisterBlock(DeepslateTiles{Cracked: true})
	world.DefaultBlockRegistry.RegisterBlock(DeepslateTiles{})
	world.DefaultBlockRegistry.RegisterBlock(Diamond{})
	world.DefaultBlockRegistry.RegisterBlock(Diorite{Polished: true})
	world.DefaultBlockRegistry.RegisterBlock(Diorite{})
	world.DefaultBlockRegistry.RegisterBlock(DirtPath{})
	world.DefaultBlockRegistry.RegisterBlock(Dirt{Coarse: true})
	world.DefaultBlockRegistry.RegisterBlock(Dirt{})
	world.DefaultBlockRegistry.RegisterBlock(DragonEgg{})
	world.DefaultBlockRegistry.RegisterBlock(DriedKelp{})
	world.DefaultBlockRegistry.RegisterBlock(Dripstone{})
	world.DefaultBlockRegistry.RegisterBlock(Emerald{})
	world.DefaultBlockRegistry.RegisterBlock(EnchantingTable{})
	world.DefaultBlockRegistry.RegisterBlock(EndBricks{})
	world.DefaultBlockRegistry.RegisterBlock(EndStone{})
	world.DefaultBlockRegistry.RegisterBlock(FletchingTable{})
	world.DefaultBlockRegistry.RegisterBlock(GlassPane{})
	world.DefaultBlockRegistry.RegisterBlock(Glass{})
	world.DefaultBlockRegistry.RegisterBlock(Glowstone{})
	world.DefaultBlockRegistry.RegisterBlock(Gold{})
	world.DefaultBlockRegistry.RegisterBlock(Granite{Polished: true})
	world.DefaultBlockRegistry.RegisterBlock(Granite{})
	world.DefaultBlockRegistry.RegisterBlock(Grass{})
	world.DefaultBlockRegistry.RegisterBlock(Gravel{})
	world.DefaultBlockRegistry.RegisterBlock(HangingRoots{})
	world.DefaultBlockRegistry.RegisterBlock(Honeycomb{})
	world.DefaultBlockRegistry.RegisterBlock(InvisibleBedrock{})
	world.DefaultBlockRegistry.RegisterBlock(IronBars{})
	world.DefaultBlockRegistry.RegisterBlock(Iron{})
	world.DefaultBlockRegistry.RegisterBlock(Jukebox{})
	world.DefaultBlockRegistry.RegisterBlock(Lapis{})
	world.DefaultBlockRegistry.RegisterBlock(Melon{})
	world.DefaultBlockRegistry.RegisterBlock(Moss{})
	world.DefaultBlockRegistry.RegisterBlock(MossCarpet{})
	world.DefaultBlockRegistry.RegisterBlock(MudBricks{})
	world.DefaultBlockRegistry.RegisterBlock(Mud{})
	world.DefaultBlockRegistry.RegisterBlock(NetherBrickFence{})
	world.DefaultBlockRegistry.RegisterBlock(NetherGoldOre{})
	world.DefaultBlockRegistry.RegisterBlock(NetherQuartzOre{})
	world.DefaultBlockRegistry.RegisterBlock(NetherSprouts{})
	world.DefaultBlockRegistry.RegisterBlock(NetherWartBlock{Warped: true})
	world.DefaultBlockRegistry.RegisterBlock(NetherWartBlock{})
	world.DefaultBlockRegistry.RegisterBlock(Netherite{})
	world.DefaultBlockRegistry.RegisterBlock(Netherrack{})
	world.DefaultBlockRegistry.RegisterBlock(Note{})
	world.DefaultBlockRegistry.RegisterBlock(Obsidian{Crying: true})
	world.DefaultBlockRegistry.RegisterBlock(Obsidian{})
	world.DefaultBlockRegistry.RegisterBlock(PackedIce{})
	world.DefaultBlockRegistry.RegisterBlock(PackedMud{})
	world.DefaultBlockRegistry.RegisterBlock(Podzol{})
	world.DefaultBlockRegistry.RegisterBlock(PolishedBlackstoneBrick{Cracked: true})
	world.DefaultBlockRegistry.RegisterBlock(PolishedBlackstoneBrick{})
	world.DefaultBlockRegistry.RegisterBlock(QuartzBricks{})
	world.DefaultBlockRegistry.RegisterBlock(RawCopper{})
	world.DefaultBlockRegistry.RegisterBlock(RawGold{})
	world.DefaultBlockRegistry.RegisterBlock(RawIron{})
	world.DefaultBlockRegistry.RegisterBlock(ReinforcedDeepslate{})
	world.DefaultBlockRegistry.RegisterBlock(RootedDirt{})
	world.DefaultBlockRegistry.RegisterBlock(Sand{Red: true})
	world.DefaultBlockRegistry.RegisterBlock(Sand{})
	world.DefaultBlockRegistry.RegisterBlock(SeaLantern{})
	world.DefaultBlockRegistry.RegisterBlock(Shroomlight{})
	world.DefaultBlockRegistry.RegisterBlock(SmithingTable{})
	world.DefaultBlockRegistry.RegisterBlock(Snow{})
	world.DefaultBlockRegistry.RegisterBlock(SoulSand{})
	world.DefaultBlockRegistry.RegisterBlock(SoulSoil{})
	world.DefaultBlockRegistry.RegisterBlock(Sponge{Wet: true})
	world.DefaultBlockRegistry.RegisterBlock(Sponge{})
	world.DefaultBlockRegistry.RegisterBlock(SporeBlossom{})
	world.DefaultBlockRegistry.RegisterBlock(Stone{Smooth: true})
	world.DefaultBlockRegistry.RegisterBlock(Stone{})
	world.DefaultBlockRegistry.RegisterBlock(TNT{})
	world.DefaultBlockRegistry.RegisterBlock(Terracotta{})
	world.DefaultBlockRegistry.RegisterBlock(Tuff{})
	world.DefaultBlockRegistry.RegisterBlock(Waterlily{})
	world.DefaultBlockRegistry.RegisterBlock(ShortGrass{})
	world.DefaultBlockRegistry.RegisterBlock(Fern{})

	for _, ore := range OreTypes() {
		world.DefaultBlockRegistry.RegisterBlock(CoalOre{Type: ore})
		world.DefaultBlockRegistry.RegisterBlock(CopperOre{Type: ore})
		world.DefaultBlockRegistry.RegisterBlock(DiamondOre{Type: ore})
		world.DefaultBlockRegistry.RegisterBlock(EmeraldOre{Type: ore})
		world.DefaultBlockRegistry.RegisterBlock(GoldOre{Type: ore})
		world.DefaultBlockRegistry.RegisterBlock(IronOre{Type: ore})
		world.DefaultBlockRegistry.RegisterBlock(LapisOre{Type: ore})
	}

	registerAll(allAnvils())
	registerAll(allAzalea())
	registerAll(allAzaleaLeaves())
	registerAll(allBanners())
	registerAll(allBarrels())
	registerAll(allBasalt())
	registerAll(allBeetroot())
	registerAll(allBlackstone())
	registerAll(allBlastFurnaces())
	registerAll(allBoneBlock())
	registerAll(allCactus())
	registerAll(allCake())
	registerAll(allCandle())
	registerAll(allCarpet())
	registerAll(allCarrots())
	registerAll(allChains())
	registerAll(allChests())
	registerAll(allCocoaBeans())
	registerAll(allComposters())
	registerAll(allConcrete())
	registerAll(allConcretePowder())
	registerAll(allCopper())
	registerAll(allCoral())
	registerAll(allCoralBlocks())
	//registerAll(allCoralFan())
	registerAll(allDeepslate())
	registerAll(allDoors())
	registerAll(allDoubleFlowers())
	registerAll(allDoubleTallGrass())
	registerAll(allEnderChests())
	registerAll(allFarmland())
	registerAll(allFence())
	registerAll(allFenceGates())
	registerAll(allFire())
	registerAll(allFlowers())
	registerAll(allFroglight())
	registerAll(allFurnaces())
	registerAll(allGlazedTerracotta())
	registerAll(allGrindstones())
	registerAll(allHayBales())
	registerAll(allItemFrames())
	registerAll(allKelp())
	registerAll(allLadders())
	registerAll(allLanterns())
	registerAll(allLava())
	registerAll(allLeaves())
	registerAll(allLecterns())
	registerAll(allLight())
	registerAll(allLitPumpkins())
	registerAll(allLogs())
	registerAll(allLooms())
	registerAll(allMelonStems())
	registerAll(allMuddyMangroveRoots())
	registerAll(allMushroom())
	registerAll(allMushroomBlock())
	registerAll(allNetherBricks())
	registerAll(allNetherWart())
	registerAll(allPlanks())
	registerAll(allPotato())
	registerAll(allPrismarine())
	registerAll(allPumpkinStems())
	registerAll(allPumpkins())
	registerAll(allPurpurs())
	registerAll(allQuartz())
	registerAll(allSandstones())
	//registerAll(allSapling())
	registerAll(allSeaPickles())
	registerAll(allSeagrass())
	registerAll(allSigns())
	registerAll(allSkulls())
	registerAll(allSlabs())
	registerAll(allSmokers())
	registerAll(allSnowLayers())
	registerAll(allStainedGlass())
	registerAll(allStainedGlassPane())
	registerAll(allStainedTerracotta())
	registerAll(allStairs())
	registerAll(allStoneBricks())
	registerAll(allStonecutters())
	registerAll(allSugarCane())
	registerAll(allTorches())
	registerAll(allTrapdoors())
	registerAll(allWalls())
	registerAll(allVines())
	registerAll(allWater())
	registerAll(allWheat())
	registerAll(allWood())
	registerAll(allWool())
	registerAll(allDecoratedPots())

	world.DefaultBlockRegistry.Finalize()
}

func init() {
	world.RegisterItem(Air{})
	world.RegisterItem(Amethyst{})
	world.RegisterItem(AncientDebris{})
	world.RegisterItem(Andesite{Polished: true})
	world.RegisterItem(Andesite{})
	world.RegisterItem(Azalea{})
	world.RegisterItem(Azalea{Flowering: true})
	world.RegisterItem(AzaleaLeaves{})
	world.RegisterItem(AzaleaLeaves{Flowering: true})
	world.RegisterItem(Barrel{})
	world.RegisterItem(Barrier{})
	world.RegisterItem(Basalt{Polished: true})
	world.RegisterItem(Basalt{})
	world.RegisterItem(Beacon{})
	world.RegisterItem(Bedrock{})
	world.RegisterItem(BeetrootSeeds{})
	world.RegisterItem(BlastFurnace{})
	world.RegisterItem(BlueIce{})
	world.RegisterItem(Bone{})
	world.RegisterItem(Bookshelf{})
	world.RegisterItem(Bricks{})
	world.RegisterItem(Cactus{})
	world.RegisterItem(Cake{})
	world.RegisterItem(Calcite{})
	world.RegisterItem(Carrot{})
	world.RegisterItem(Chain{})
	world.RegisterItem(Chest{})
	world.RegisterItem(ChiseledQuartz{})
	world.RegisterItem(Clay{})
	world.RegisterItem(Coal{})
	world.RegisterItem(Cobblestone{Mossy: true})
	world.RegisterItem(Cobblestone{})
	world.RegisterItem(CocoaBean{})
	world.RegisterItem(Composter{})
	world.RegisterItem(CraftingTable{})
	world.RegisterItem(DeadBush{})
	world.RegisterItem(DeepslateBricks{Cracked: true})
	world.RegisterItem(DeepslateBricks{})
	world.RegisterItem(DeepslateTiles{Cracked: true})
	world.RegisterItem(DeepslateTiles{})
	world.RegisterItem(Diamond{})
	world.RegisterItem(Diorite{Polished: true})
	world.RegisterItem(Diorite{})
	world.RegisterItem(DirtPath{})
	world.RegisterItem(Dirt{Coarse: true})
	world.RegisterItem(Dirt{})
	world.RegisterItem(DragonEgg{})
	world.RegisterItem(DriedKelp{})
	world.RegisterItem(Dripstone{})
	world.RegisterItem(Emerald{})
	world.RegisterItem(EnchantingTable{})
	world.RegisterItem(EndBricks{})
	world.RegisterItem(EndStone{})
	world.RegisterItem(EnderChest{})
	world.RegisterItem(Farmland{})
	world.RegisterItem(Furnace{})
	world.RegisterItem(GlassPane{})
	world.RegisterItem(Glass{})
	world.RegisterItem(Glowstone{})
	world.RegisterItem(Gold{})
	world.RegisterItem(Granite{Polished: true})
	world.RegisterItem(Granite{})
	world.RegisterItem(Grass{})
	world.RegisterItem(Gravel{})
	world.RegisterItem(Grindstone{})
	world.RegisterItem(HangingRoots{})
	world.RegisterItem(HayBale{})
	world.RegisterItem(Honeycomb{})
	world.RegisterItem(InvisibleBedrock{})
	world.RegisterItem(IronBars{})
	world.RegisterItem(Iron{})
	world.RegisterItem(ItemFrame{Glowing: true})
	world.RegisterItem(ItemFrame{})
	world.RegisterItem(Jukebox{})
	world.RegisterItem(Kelp{})
	world.RegisterItem(Ladder{})
	world.RegisterItem(Lapis{})
	world.RegisterItem(Lectern{})
	world.RegisterItem(LitPumpkin{})
	world.RegisterItem(Loom{})
	world.RegisterItem(MelonSeeds{})
	world.RegisterItem(Melon{})
	world.RegisterItem(Moss{})
	world.RegisterItem(MossCarpet{})
	world.RegisterItem(MudBricks{})
	world.RegisterItem(MuddyMangroveRoots{})
	world.RegisterItem(Mud{})
	world.RegisterItem(NetherBrickFence{})
	world.RegisterItem(NetherGoldOre{})
	world.RegisterItem(NetherQuartzOre{})
	world.RegisterItem(NetherSprouts{})
	world.RegisterItem(NetherWartBlock{Warped: true})
	world.RegisterItem(NetherWartBlock{})
	world.RegisterItem(NetherWart{})
	world.RegisterItem(Netherite{})
	world.RegisterItem(Netherrack{})
	world.RegisterItem(Note{Pitch: 24})
	world.RegisterItem(Obsidian{Crying: true})
	world.RegisterItem(Obsidian{})
	world.RegisterItem(PackedIce{})
	world.RegisterItem(PackedMud{})
	world.RegisterItem(Podzol{})
	world.RegisterItem(PolishedBlackstoneBrick{Cracked: true})
	world.RegisterItem(PolishedBlackstoneBrick{})
	world.RegisterItem(Potato{})
	world.RegisterItem(PumpkinSeeds{})
	world.RegisterItem(Pumpkin{Carved: true})
	world.RegisterItem(Pumpkin{})
	world.RegisterItem(PurpurPillar{})
	world.RegisterItem(Purpur{})
	world.RegisterItem(QuartzBricks{})
	world.RegisterItem(QuartzPillar{})
	world.RegisterItem(Quartz{Smooth: true})
	world.RegisterItem(Quartz{})
	world.RegisterItem(RawCopper{})
	world.RegisterItem(RawGold{})
	world.RegisterItem(RawIron{})
	world.RegisterItem(ReinforcedDeepslate{})
	world.RegisterItem(RootedDirt{})
	world.RegisterItem(Sand{Red: true})
	world.RegisterItem(Sand{})
	world.RegisterItem(SeaLantern{})
	world.RegisterItem(SeaPickle{})
	world.RegisterItem(Shroomlight{})
	world.RegisterItem(SmithingTable{})
	world.RegisterItem(Smoker{})
	world.RegisterItem(Snow{})
	world.RegisterItem(SoulSand{})
	world.RegisterItem(SoulSoil{})
	world.RegisterItem(Sponge{Wet: true})
	world.RegisterItem(Sponge{})
	world.RegisterItem(SporeBlossom{})
	world.RegisterItem(Stonecutter{})
	world.RegisterItem(Stone{Smooth: true})
	world.RegisterItem(Stone{})
	world.RegisterItem(SugarCane{})
	world.RegisterItem(TNT{})
	world.RegisterItem(Terracotta{})
	world.RegisterItem(Tuff{})
	world.RegisterItem(Waterlily{})
	world.RegisterItem(Vines{})
	world.RegisterItem(WheatSeeds{})
	world.RegisterItem(DecoratedPot{})
	world.RegisterItem(ShortGrass{})
	world.RegisterItem(Fern{})
	world.RegisterItem(item.Bucket{Content: item.LiquidBucketContent(Lava{})})
	world.RegisterItem(item.Bucket{Content: item.LiquidBucketContent(Water{})})
	world.RegisterItem(item.Bucket{Content: item.MilkBucketContent()})

	for _, b := range allLight() {
		world.RegisterItem(b.(world.Item))
	}
	for _, c := range allCoral() {
		world.RegisterItem(c.(world.Item))
	}
	for _, c := range allCoralBlocks() {
		world.RegisterItem(c.(world.Item))
	}
	for _, c := range allCoralFan() {
		world.RegisterItem(c.(world.Item))
	}
	for _, t := range SandstoneTypes() {
		world.RegisterItem(Sandstone{Type: t, Red: true})
		world.RegisterItem(Sandstone{Type: t})
	}
	for _, s := range allStoneBricks() {
		world.RegisterItem(s.(world.Item))
	}
	for _, t := range AnvilTypes() {
		world.RegisterItem(Anvil{Type: t})
	}
	for _, c := range item.Colours() {
		world.RegisterItem(Banner{Colour: c})
		world.RegisterItem(Carpet{Colour: c})
		world.RegisterItem(ConcretePowder{Colour: c})
		world.RegisterItem(Concrete{Colour: c})
		world.RegisterItem(GlazedTerracotta{Colour: c})
		world.RegisterItem(StainedGlassPane{Colour: c})
		world.RegisterItem(StainedGlass{Colour: c})
		world.RegisterItem(StainedTerracotta{Colour: c})
		world.RegisterItem(Wool{Colour: c})
	}
	for _, w := range WoodTypes() {
		if w != WarpedWood() && w != CrimsonWood() {
			world.RegisterItem(Leaves{Wood: w, Persistent: true})
		}
		world.RegisterItem(Log{Wood: w, Stripped: true})
		world.RegisterItem(Log{Wood: w})
		world.RegisterItem(Planks{Wood: w})
		world.RegisterItem(Sign{Wood: w})
		world.RegisterItem(WoodDoor{Wood: w})
		world.RegisterItem(WoodFenceGate{Wood: w})
		world.RegisterItem(WoodFence{Wood: w})
		world.RegisterItem(WoodTrapdoor{Wood: w})
		world.RegisterItem(Wood{Wood: w, Stripped: true})
		world.RegisterItem(Wood{Wood: w})
		world.RegisterItem(Sapling{Wood: w})
	}
	for _, ore := range OreTypes() {
		world.RegisterItem(CoalOre{Type: ore})
		world.RegisterItem(CopperOre{Type: ore})
		world.RegisterItem(DiamondOre{Type: ore})
		world.RegisterItem(EmeraldOre{Type: ore})
		world.RegisterItem(GoldOre{Type: ore})
		world.RegisterItem(IronOre{Type: ore})
		world.RegisterItem(LapisOre{Type: ore})
	}
	for _, f := range FireTypes() {
		world.RegisterItem(Lantern{Type: f})
		world.RegisterItem(Torch{Type: f})
	}
	for _, f := range FlowerTypes() {
		world.RegisterItem(Flower{Type: f})
	}
	for _, f := range DoubleFlowerTypes() {
		world.RegisterItem(DoubleFlower{Type: f})
	}
	for _, g := range DoubleTallGrassTypes() {
		world.RegisterItem(DoubleTallGrass{Type: g})
	}
	for _, p := range PrismarineTypes() {
		world.RegisterItem(Prismarine{Type: p})
	}
	for _, t := range NetherBricksTypes() {
		world.RegisterItem(NetherBricks{Type: t})
	}
	for _, t := range FroglightTypes() {
		world.RegisterItem(Froglight{Type: t})
	}
	for _, s := range SkullTypes() {
		world.RegisterItem(Skull{Type: s})
	}
	for _, t := range SlabBlocks() {
		world.RegisterItem(Slab{Block: t})
	}
	for _, t := range WallBlocks() {
		world.RegisterItem(Wall{Block: t})
	}
	for _, s := range StairsBlocks() {
		world.RegisterItem(Stairs{Block: s})
	}
	for _, t := range BlackstoneTypes() {
		world.RegisterItem(Blackstone{Type: t})
	}
	for _, t := range DeepslateTypes() {
		world.RegisterItem(Deepslate{Type: t})
	}
	for _, t := range MushroomTypes() {
		world.RegisterItem(MushroomBlock{Type: t})
		world.RegisterItem(Mushroom{Type: t})
	}
	for _, c := range allCopper() {
		world.RegisterItem(c.(world.Item))
	}

	world.RegisterItem(Candle{Dyed: false})
	for _, c := range item.Colours() {
		world.RegisterItem(Candle{Colour: c, Dyed: true})
	}
}

func registerAll(blocks []world.Block) {
	for _, b := range blocks {
		world.DefaultBlockRegistry.RegisterBlock(b)
	}
}
